name: Update TODO backlinks
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3
    - name: todo-backlinks
      uses: j2kun/todo-backlinks@0eb911e9842161b528b3aea45e9983533e655dfc # pin@v0.0.4
      env:
        GITHUB_TOKEN: ${{ github.token }}
